### ISSUE TITLE
About the database engine

### ISSUE THREAD

**Issue by Annwenn** [felipesere/faros#61]
Hi! I'm planning to set up an installation of faros for a community, and I was wondering what was the actual database engine used in Faros.
I see you can use it with MySQL, but what about PostgreSQL or other ones? And are there specific commands to enter to set up the database first? Or is everything automated?

**Comment by felipesere** [comment]
I strongly suggest looking at http://faros.io first. Its far from ready to be used for real.
Currently its a hobby project to play with Elixir, Phoenix and Docker :smile_cat: 

We have not tried it with Postgres. You'd have to change the `adapter` setting in the config.
If you want to try it, I recommend pulling down the code, changing the prod config, adding a different image to `docker-compose.yaml` and then running it with `docker-compose up`.
The migrations are run at application boot. Let me know if you need any help.

Oh and feel free to look at the issues and open PRs :)

**Comment by Annwenn** [comment]
Hi, and thanks for the answer!
I want to try not using Docker for the isolation and using FreeBSD Jails instead, that'd be fun :heart: 
I already have a Postgres running for [hrefhref/news](https://github.com/hrefhref/news) so I think I'll optimize the existing installation.
Thanks for the tip and have a [good night UGT](www.total-knowledge.com/~ilya/mips/ugt.html).
