### ISSUE TITLE
Create an admin page

### ISSUE THREAD

**Issue by felipesere** [felipesere/faros#63]
To be able to add/remove any entity quickly we should probably create something like an admin page.
Right now we have a couple of entries in the books table that can not be deleted because they have no `slug`.

I would probably also move creating/deleting of categories to there.

**Comment by felipesere** [comment]
Depends on #44

**Comment by Annwenn** [comment]
How about using https://github.com/h4cc/slugger to generate the slugs and truncating at some point?

**Comment by felipesere** [comment]
Funny enough, I called the module with my "rules for slugs" `Slugger`.

Thanks for recommending this @Annwenn

**Comment by Annwenn** [comment]
My pleasure ;)
[awesome-elixir](https://github.com/h4cc/awesome-elixir/) is a good starting point when one's looking for libraries
