### ISSUE TITLE
Add ability to tag a book.

### ISSUE THREAD

**Issue by marosluuce** [felipesere/faros#7]
Books should be able to have an arbitrary number of tags.
They should searchable by each tag.

**Comment by heruku** [comment]
I find tags useful only when there's a limited number of them. If we allow arbitrary tags, I can see multiple books having similar tags that mean the same thing but are not searchable together. For example:

POODR - tagged with 'OO'
PPP       - tagged with 'Object-oriented design'

This is what bothers me about many tagging systems to the point that the tags become a distraction. Any thoughts, ideas on how to have proper tagging that actually works and helps people out?

**Comment by marosluuce** [comment]
Would it make sense to make it easy to curate? There could be a page where you can see a list of all tags. From there you select tags and update all associated items use one of them or a new one. It still requires that someone take a look at it from time to time.

Maybe a better alternative is having topics. A topic could be a collection of items in lighthouse, possibly containing topics themselves. You might run into some similar problems, but it might help the problem of categorization better.

**Comment by felipesere** [comment]
On an admin page we could list both the x most used tags and the ones that have only a single 'entity' attached. I guess just seeing them and then editing it will help.
Also, we can add suggestions based on existing tags.
